# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.cache/wt [current_project]
set_property parent.project_path C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.runs/c_accum_0_synth_1/c_accum_0.dcp
set_property used_in_implementation false [get_files C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.runs/c_accum_0_synth_1/c_accum_0.dcp]
read_vhdl -library xil_defaultlib C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.srcs/sources_1/new/acc.vhd
read_xdc C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.srcs/constrs_1/imports/ECEC-302-Assignments/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/lc599.DREXEL/Desktop/Accumulator/Accumulator.srcs/constrs_1/imports/ECEC-302-Assignments/Basys3_Master.xdc]

catch { write_hwdef -file acc.hwdef }
synth_design -top acc -part xc7a35tcpg236-1
write_checkpoint -noxdef acc.dcp
catch { report_utilization -file acc_utilization_synth.rpt -pb acc_utilization_synth.pb }
