# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lc599/register_bank_stage_3/register_bank_stage_2.cache/wt [current_project]
set_property parent.project_path C:/Users/lc599/register_bank_stage_3/register_bank_stage_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/lc599/register_bank_stage_3/register_bank_stage_2.srcs/sources_1/new/reg_v2.vhd
read_xdc C:/Users/lc599/register_bank_stage_3/register_bank_stage_2.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lc599/register_bank_stage_3/register_bank_stage_2.srcs/constrs_1/new/constraints.xdc]

catch { write_hwdef -file reg_v3.hwdef }
synth_design -top reg_v3 -part xc7a35tcpg236-1
write_checkpoint -noxdef reg_v3.dcp
catch { report_utilization -file reg_v3_utilization_synth.rpt -pb reg_v3_utilization_synth.pb }
