# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lc599/Desktop/exam2/exam2.cache/wt [current_project]
set_property parent.project_path C:/Users/lc599/Desktop/exam2/exam2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lc599/Desktop/exam2/exam2.srcs/sources_1/new/pe.vhd
  C:/Users/lc599/Desktop/exam2/exam2.srcs/sources_1/new/max_array.vhd
  C:/Users/lc599/Desktop/exam2/exam2.srcs/sources_1/new/max_array_5x3.vhd
}
read_xdc C:/Users/lc599/Desktop/exam2/exam2.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/lc599/Desktop/exam2/exam2.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]

catch { write_hwdef -file max_array_5x3.hwdef }
synth_design -top max_array_5x3 -part xc7a35tcpg236-1
write_checkpoint -noxdef max_array_5x3.dcp
catch { report_utilization -file max_array_5x3_utilization_synth.rpt -pb max_array_5x3_utilization_synth.pb }
