# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pcc37/regStuff/regStuff.cache/wt [current_project]
set_property parent.project_path C:/Users/pcc37/regStuff/regStuff.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/pcc37/regStuff/regStuff.srcs/sources_1/new/reg.vhd
  C:/Users/pcc37/regStuff/regStuff.srcs/sources_1/new/reg4.vhd
}
read_xdc {{E:/school work/ECEC302/basys shit/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{E:/school work/ECEC302/basys shit/Basys3_Master.xdc}}]

catch { write_hwdef -file reg4.hwdef }
synth_design -top reg4 -part xc7a35tcpg236-1
write_checkpoint -noxdef reg4.dcp
catch { report_utilization -file reg4_utilization_synth.rpt -pb reg4_utilization_synth.pb }
