# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lc599/cascading_registers/cascading_registers.cache/wt [current_project]
set_property parent.project_path C:/Users/lc599/cascading_registers/cascading_registers.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lc599/cascading_registers/cascading_registers.srcs/sources_1/new/reg.vhd
  C:/Users/lc599/cascading_registers/cascading_registers.srcs/sources_1/new/cascade_reg4.vhd
}
read_xdc C:/Users/lc599/cascading_registers/cascading_registers.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lc599/cascading_registers/cascading_registers.srcs/constrs_1/new/constraints.xdc]

catch { write_hwdef -file cascade_reg4.hwdef }
synth_design -top cascade_reg4 -part xc7a35tcpg236-1
write_checkpoint -noxdef cascade_reg4.dcp
catch { report_utilization -file cascade_reg4_utilization_synth.rpt -pb cascade_reg4_utilization_synth.pb }
